version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      - run:
          name: Install packages
          command:
            sudo apt-get update && sudo apt-get install wget zip unzip python2.7 python-pip -y

      - run:
          name: Install curl & npm
          command: |
            sudo apt install curl -y
            sudo apt install npm -y

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6'

      - run:
          name: Install awscli
          command: |
            sudo pip install awscli
            aws configure set default.region us-east-1
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY}
            aws configure set aws_secret_access_key ${AWS_SECRET_KEY}
      - run:
          name: Build Artifact
          command: |
            cd webapp
            pwd
            ls -al
            cd ..
            pwd
      - run:
          name: Zip Artifact
          command: |
            echo "current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            mkdir -p codedeploy_artifact
            pwd
            cd codedeploy_artifact
            cp -r ../infrastructure .
            cp -r ../webapp .
            cp -r ../.circleci .
            cp ../*.yml .
            cp ../*.md .
            cp ../LICENSE .
            cp ../.gitignore .
            pwd
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip .
            ls -al
            pwd
            cd ..
            pwd
            ls -al
            cd codedeploy_artifact
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            pwd
            ls -al
            cd codedeploy_artifact
            aws configure list
            aws s3 cp csye6225-web-app-${CIRCLE_BUILD_NUM}.zip s3://${CODE_DEPLOY_S3_BUCKET}
      - run:
          name: Make CodeDeploy API call
          command: |
            aws deploy create-deployment --output json --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name csye6225-webapp-deployment --s3-location bucket=${CODE_DEPLOY_S3_BUCKET},bundleType=zip,key=csye6225-web-app-${CIRCLE_BUILD_NUM}.zip
